# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: hardhat test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    environment: hardhat tests
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install command-line deps
      run: sudo apt install jq

    - name: Install hardhat/node packages
      run: npm install

    - name: Create dotenv file
      run: cp .github/workflows/env_github_actions .env

    - name: Compile contracts
      run: npx hardhat compile

    - name: Run tests using the fork specified by hardhat.config.js
      run: npx hardhat test

    - name: Get the latest block on Polygon mainnet and specify RPC as env var
      run: |
        echo RPC_URL=https://polygon-rpc.com >> $GITHUB_ENV 
        echo LATEST_BLOCK_NUMBER=`curl https://polygon-rpc.com -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' | jq  -r .result` >> $GITHUB_ENV        

    - name: Set the block number to fork from
      # Use a slightly older block with 64 confirmations
      run: echo RECENT_BLOCK_NUMBER=$(($LATEST_BLOCK_NUMBER - 0x40)) >> $GITHUB_ENV

    - name: Run tests on a fork from a very recent block
      run: |
        echo "Forking from block number ${RECENT_BLOCK_NUMBER}"
        npx hardhat node --fork $RPC_URL --fork-block-number $RECENT_BLOCK_NUMBER > /dev/null &
        sleep 2
        npx hardhat test --network localhost
